INSERT PVK_STATUS_TYPE_LKUP (STATUS_TYPE_CD, STATUS_TYPE_DESC) VALUES ('ACT','Active');
INSERT PVK_STATUS_TYPE_LKUP (STATUS_TYPE_CD, STATUS_TYPE_DESC) VALUES ('DCT','De-Active');

INSERT PVK_USER_TYPE_LKUP (USER_TYPE_CD, USER_TYPE_DESC) VALUES ('SALES','SALES AGENTS');
INSERT PVK_USER_TYPE_LKUP (USER_TYPE_CD, USER_TYPE_DESC) VALUES ('CUSTOMER','CUSTOMER AGENTS');
INSERT PVK_USER_TYPE_LKUP (USER_TYPE_CD, USER_TYPE_DESC) VALUES ('SUPPLIER','SUPPLIER AGENTS');
INSERT PVK_USER_TYPE_LKUP (USER_TYPE_CD, USER_TYPE_DESC) VALUES ('ADMIN','ADMINISTRATOR USERS');
INSERT PVK_USER_TYPE_LKUP (USER_TYPE_CD, USER_TYPE_DESC) VALUES ('CORP','CORPARATE USERSs');

INSERT PVK_UUID_TYPE_LKUP (UUID_TYPE_CD, UUID_TYPE_DESC) VALUES ('ADHAR','INDIAN ADHAR CARD');
INSERT PVK_UUID_TYPE_LKUP (UUID_TYPE_CD, UUID_TYPE_DESC) VALUES ('ITIN','INDIAN TAX IDENTIFICATION');
INSERT PVK_UUID_TYPE_LKUP (UUID_TYPE_CD, UUID_TYPE_DESC) VALUES ('PAN','INDIAN PAN CARDS');

INSERT PVK_ADDRESS_TYPE_LKUP (ADDRESS_TYPE_CD, ADDRESS_TYPE_DESC) VALUES ('PRIMARY','Primary Address');
INSERT PVK_ADDRESS_TYPE_LKUP (ADDRESS_TYPE_CD, ADDRESS_TYPE_DESC) VALUES ('HOME','Home Address');
INSERT PVK_ADDRESS_TYPE_LKUP (ADDRESS_TYPE_CD, ADDRESS_TYPE_DESC) VALUES ('OFFICE','Office Address');

INSERT PVK_PHONE_TYPE_LKUP (PHONE_TYPE_CD, PHONE_TYPE_DESC) VALUES ('MOBILE','Mobile Phone');

INSERT PVK_OWNER_LKUP (OWNER_CD, OWNER_NAME) VALUES ('USER','PVK_USER');
INSERT PVK_OWNER_LKUP (OWNER_CD, OWNER_NAME) VALUES ('CUSTOMER','PVK_CUSTOMER');
INSERT PVK_OWNER_LKUP (OWNER_CD, OWNER_NAME) VALUES ('SUPPLIER','PVK_SUPPLIER');
INSERT PVK_OWNER_LKUP (OWNER_CD, OWNER_NAME) VALUES ('BRANCH','PVK_BRANCH');