CREATE USER 'pvkfoods'@'localhost' IDENTIFIED BY 'pvkfoods';
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP ON pvkfoods.*  TO 'pvkfoods'@'localhost';

CREATE TABLE PVK_PRODUCT (PRODUCT_ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT, PRODUCT_DESC VARCHAR(250) NOT NULL, 
	PRODUCT_STATUS VARCHAR(1) NOT NULL,PRODUCT_UNIT DECIMAL(5,2), UPDATED_BY VARCHAR(100), UPDATED_DATE DATE );

CREATE TABLE PVK_CUSTOMER (CUSTOMER_ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT, 
	CUSTOMER_NAME VARCHAR(250) NOT NULL, EMAIL VARCHAR(100) NOT NULL, ADDRESS VARCHAR(100), PHONE VARCHAR(20), UPDATED_BY VARCHAR(100), UPDATED_DATE DATE );

