//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.02 at 10:36:05 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://beans.dto.pvkfoods.com")
package com.pvkfoods.dto.beans;
