//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.04 at 02:34:55 PM EST 
//


package com.pvkfoods.dto.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BaseRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="prams" type="{http://request.dto.pvkfoods.com}RequestParams"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseRequest", propOrder = {
    "prams"
})
@XmlSeeAlso({
    CustomerRequest.class,
    GetOrderRequest.class,
    OrderRequest.class,
    OrderSearchRequest.class,
    ProductRequest.class
})
public class BaseRequest {

    @XmlElement(required = true)
    protected RequestParams prams;

    /**
     * Gets the value of the prams property.
     * 
     * @return
     *     possible object is
     *     {@link RequestParams }
     *     
     */
    public RequestParams getPrams() {
        return prams;
    }

    /**
     * Sets the value of the prams property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestParams }
     *     
     */
    public void setPrams(RequestParams value) {
        this.prams = value;
    }

}
