//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.06 at 12:20:16 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://request.dto.pvkfoods.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.pvkfoods.dto.request;
